package com.veridian.agent.config;

import com.veridian.agent.entity.KnowledgeBase;
import com.veridian.agent.entity.SupportRequest;
import com.veridian.agent.entity.Ticket;
import com.veridian.agent.repository.KnowledgeBaseRepository;
import com.veridian.agent.repository.SupportRequestRepository;
import com.veridian.agent.repository.TicketRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class SeedData {
    @Bean
    CommandLineRunner seed(
        KnowledgeBaseRepository knowledgeRepository,
        SupportRequestRepository requestRepository,
        TicketRepository ticketRepository
    ) {
        return args -> {
            seedPolicies(knowledgeRepository);
            seedTicketHistory(requestRepository, ticketRepository);
            seedAssignmentRequests(requestRepository);
        };
    }

    private void seedPolicies(KnowledgeBaseRepository repository) {
        List<KnowledgeBase> policies = List.of(
            policy(
                "KB-01", "Password Reset",
                "Employees can reset their own password via the self-service portal at any time. "
                    + "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
                    + "No approval required."
            ),
            policy(
                "KB-02", "VPN Access",
                "VPN access is granted automatically to all full-time employees. Contractors require manager "
                    + "approval submitted via the access request form. VPN credentials expire every 90 days and "
                    + "must be renewed by the employee."
            ),
            policy(
                "KB-03", "Laptop Replacement",
                "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified "
                    + "hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
            ),
            policy(
                "KB-04", "Software Installation Requests",
                "Standard software listed in the approved catalog can be self-installed. Non-catalog software "
                    + "requires IT Security review. Security review takes 3-5 business days."
            ),
            policy(
                "KB-05", "Printer Troubleshooting",
                "For printer issues: check the printer queue; restart the print spooler; if the issue persists "
                    + "after restart, log a ticket with the printer's asset tag."
            ),
            policy(
                "KB-06", "Email Mailbox Quota",
                "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases "
                    + "beyond 25GB require manager approval. Maximum quota is 50GB."
            ),
            policy(
                "KB-07", "Guest Wi-Fi Access",
                "Guest Wi-Fi credentials are valid for 24 hours. They can be generated by any employee from the "
                    + "front-desk kiosk. No IT ticket is required."
            ),
            policy(
                "KB-08", "Expense Software Access",
                "Access to the expense management tool is granted by Finance, not IT. IT can only assist with "
                    + "login/technical issues once an account already exists."
            ),
            policy(
                "KB-09", "Security Incident Reporting",
                "Any suspected phishing email, malware, or unauthorized access attempt must be reported to "
                    + "security@veridian-corp.example immediately. The suspicious email should NOT be forwarded "
                    + "to other employees."
            ),
            policy(
                "KB-10", "Work-From-Home Equipment",
                "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment "
                    + "allowance: chair or monitor. Requires manager sign-off and Finance processing. IT only handles "
                    + "the equipment shipping request once approved."
            ),
            policy(
                "ASSET-MANAGEMENT", "Asset Management Policy",
                "Issued by Finance & Assets. Last updated Q2 2026. All company-issued hardware, including laptops "
                    + "and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement "
                    + "outside this cycle requires Finance sign-off in addition to IT approval. Do not interpret this "
                    + "policy as overriding KB-03 eligibility after 3 years or verified hardware failure."
            )
        );

        repository.deleteByPolicyId("KB-EXPENSE");
        for (KnowledgeBase policy : policies) {
            repository.findByPolicyId(policy.getPolicyId()).ifPresentOrElse(existing -> {
                existing.setTitle(policy.getTitle());
                existing.setContent(policy.getContent());
                repository.save(existing);
            }, () -> repository.save(policy));
        }
    }

    private void seedTicketHistory(
        SupportRequestRepository requestRepository,
        TicketRepository ticketRepository
    ) {
        List<HistorySeed> history = List.of(
            new HistorySeed("TK-1042", "R. Verma", "VPN credential expired", "Resolved (closed)"),
            new HistorySeed("TK-1043", "S. Iyer", "Laptop replacement (3.2 yrs old)", "Approved - pending fulfillment (active)"),
            new HistorySeed("TK-1044", "A. Khan", "Non-catalog software request", "Pending Security review (active)"),
            new HistorySeed("TK-1045", "P. Joshi", "Mailbox quota increase", "Approved at 35GB (closed)"),
            new HistorySeed("TK-1046", "M. Das", "Printer paper jam, floor 2", "Resolved (closed)"),
            new HistorySeed("TK-1047", "K. Singh", "Home office equipment request", "Pending Finance (active)"),
            new HistorySeed("TK-1048", "T. Rao", "Phishing email reported", "Escalated to Security - under investigation (active)"),
            new HistorySeed("TK-1049", "V. Nambiar", "Password reset", "Resolved (closed)"),
            new HistorySeed("TK-1050", "J. Fernandes", "Admin access request", "Rejected - no business justification provided (closed)"),
            new HistorySeed("TK-1051", "L. Menon", "Guest Wi-Fi issued", "Resolved (closed)")
        );

        for (HistorySeed item : history) {
            if (ticketRepository.findByReferenceCode(item.ticketCode()).isPresent()) {
                continue;
            }

            String email = item.employeeName().toLowerCase().replace(" ", ".")
                + "@veridian-corp.example";
            SupportRequest request = requestRepository.save(
                new SupportRequest(item.employeeName(), email, item.issue())
            );
            request.setRequestCode(item.ticketCode());
            request.setInitialAction(item.status());
            requestRepository.save(request);

            Ticket ticket = new Ticket(
                request,
                ticketStatus(item.status()),
                "HISTORY",
                "MEDIUM",
                ticketOwner(item.issue()),
                item.status()
            );
            ticket.setReferenceCode(item.ticketCode());
            ticket.setIssueSummary(item.issue());
            ticketRepository.save(ticket);
        }
    }

    private void seedAssignmentRequests(SupportRequestRepository repository) {
        List<AssignmentSeed> requests = List.of(
            new AssignmentSeed("REQ-01", "Aditi Sharma", "aditi.sharma@veridian-corp.example", "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now.", "Not started"),
            new AssignmentSeed("REQ-02", "Vikram Chawla", "vikram.chawla@veridian-corp.example", "Can I get Wi-Fi access for a guest visiting our office tomorrow?", "Not started"),
            new AssignmentSeed("REQ-03", "Karan Mehta", "karan.mehta@veridian-corp.example", "I'm locked out of my account, tried my password 6 times.", "In progress - reset queued"),
            new AssignmentSeed("REQ-04", "Ritu Bhatia", "ritu.bhatia@veridian-corp.example", "Need approval to install a data-analysis tool that's not in the software catalog.", "Waiting on Security review"),
            new AssignmentSeed("REQ-05", "Sanjay Oberoi", "sanjay.oberoi@veridian-corp.example", "My VPN stopped working this morning, says credentials expired.", "Not started"),
            new AssignmentSeed("REQ-06", "Meera Iyer", "meera.iyer@veridian-corp.example", "Printer on the 3rd floor keeps showing paper jam even though there's no jam.", "Investigating - technician assigned"),
            new AssignmentSeed("REQ-07", "Farhan Ali", "farhan.ali@veridian-corp.example", "I've started working from home 4 days a week, how do I get a monitor?", "Not started"),
            new AssignmentSeed("REQ-08", "Ananya Reddy", "ananya.reddy@veridian-corp.example", "I think I got a phishing email asking for my login - forwarding it to a few teammates to check.", "Escalated to Security (auto-flagged)"),
            new AssignmentSeed("REQ-09", "Rohit Desai", "rohit.desai@veridian-corp.example", "My mailbox is full and I can't send emails.", "Not started"),
            new AssignmentSeed("REQ-10", "Kavya Pillai", "kavya.pillai@veridian-corp.example", "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.", "Not started"),
            new AssignmentSeed("REQ-11", "Nikhil Bansal", "nikhil.bansal@veridian-corp.example", "New contractor joining my team next week, they'll need VPN access.", "Not started"),
            new AssignmentSeed("REQ-12", "Sneha Kulkarni", "sneha.kulkarni@veridian-corp.example", "I can't log into the expense tool, keeps saying invalid credentials.", "Waiting on employee response"),
            new AssignmentSeed("REQ-13", "Aman Gupta", "aman.gupta@veridian-corp.example", "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.", "Not started"),
            new AssignmentSeed("REQ-14", "Tanya Chopra", "tanya.chopra@veridian-corp.example", "Requesting approval to install a browser extension for productivity tracking.", "Not started"),
            new AssignmentSeed("REQ-15", "Rahul Menon", "rahul.menon@veridian-corp.example", "Hey can you help, it's not working.", "Not started")
        );

        for (AssignmentSeed item : requests) {
            if (repository.findByRequestCode(item.requestCode()).isPresent()) {
                continue;
            }

            SupportRequest request = new SupportRequest(
                item.employeeName(), item.employeeEmail(), item.message()
            );
            request.setRequestCode(item.requestCode());
            request.setInitialAction(item.initialAction());
            repository.save(request);
        }
    }

    private KnowledgeBase policy(String id, String title, String content) {
        return new KnowledgeBase(id, title, content);
    }

    private String ticketStatus(String status) {
        if (status.contains("active")) {
            return "PENDING_REVIEW";
        }
        if (status.contains("Resolved") || status.contains("Approved") || status.contains("Rejected")) {
            return "RESOLVED";
        }
        return "ESCALATED";
    }

    private String ticketOwner(String issue) {
        String lowerCaseIssue = issue.toLowerCase();
        if (lowerCaseIssue.contains("phishing")) {
            return "Security";
        }
        if (lowerCaseIssue.contains("finance")
            || lowerCaseIssue.contains("mailbox")
            || lowerCaseIssue.contains("home")) {
            return "Finance";
        }
        return "IT";
    }

    private record HistorySeed(String ticketCode, String employeeName, String issue, String status) {}

    private record AssignmentSeed(
        String requestCode,
        String employeeName,
        String employeeEmail,
        String message,
        String initialAction
    ) {}
}
